### ISSUE TITLE
CodingBat - String1

### ISSUE THREAD

**Issue by divinedragon** [divinedragon/code-challenges-java#126]
## Tasklist
```[tasklist]
### Tasks
- [x] https://github.com/divinedragon/code-challenges-java/issues/93
- [x] https://github.com/divinedragon/code-challenges-java/issues/94
- [x] https://github.com/divinedragon/code-challenges-java/issues/95
- [x] https://github.com/divinedragon/code-challenges-java/issues/96
- [x] https://github.com/divinedragon/code-challenges-java/issues/97
- [x] https://github.com/divinedragon/code-challenges-java/issues/98
- [x] https://github.com/divinedragon/code-challenges-java/issues/99
- [x] https://github.com/divinedragon/code-challenges-java/issues/100
- [x] https://github.com/divinedragon/code-challenges-java/issues/101
- [x] https://github.com/divinedragon/code-challenges-java/issues/102
- [x] https://github.com/divinedragon/code-challenges-java/issues/103
- [x] https://github.com/divinedragon/code-challenges-java/issues/104
- [x] https://github.com/divinedragon/code-challenges-java/issues/105
- [x] https://github.com/divinedragon/code-challenges-java/issues/106
- [x] https://github.com/divinedragon/code-challenges-java/issues/107
- [x] https://github.com/divinedragon/code-challenges-java/issues/108
- [x] https://github.com/divinedragon/code-challenges-java/issues/109
- [x] https://github.com/divinedragon/code-challenges-java/issues/110
- [x] https://github.com/divinedragon/code-challenges-java/issues/111
- [x] https://github.com/divinedragon/code-challenges-java/issues/112
- [x] https://github.com/divinedragon/code-challenges-java/issues/113
- [x] https://github.com/divinedragon/code-challenges-java/issues/114
- [x] https://github.com/divinedragon/code-challenges-java/issues/115
- [x] https://github.com/divinedragon/code-challenges-java/issues/116
- [x] https://github.com/divinedragon/code-challenges-java/issues/117
- [x] https://github.com/divinedragon/code-challenges-java/issues/118
- [x] https://github.com/divinedragon/code-challenges-java/issues/119
- [x] https://github.com/divinedragon/code-challenges-java/issues/120
- [x] https://github.com/divinedragon/code-challenges-java/issues/121
- [x] https://github.com/divinedragon/code-challenges-java/issues/122
- [x] https://github.com/divinedragon/code-challenges-java/issues/123
- [x] https://github.com/divinedragon/code-challenges-java/issues/124
- [x] https://github.com/divinedragon/code-challenges-java/issues/125
```

## Issues in the Epic
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98
- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103
- [x] #104
- [x] #105
- [x] #106
- [x] #107
- [x] #108
- [x] #109
- [x] #110
- [x] #111
- [x] #112
- [x] #113
- [x] #114
- [x] #115
- [x] #116
- [x] #117
- [x] #118
- [x] #119
- [x] #120
- [x] #121
- [x] #122
- [x] #123
- [x] #124
- [x] #125
