### ISSUE TITLE
CodingBat - Array1

### ISSUE THREAD

**Issue by divinedragon** [divinedragon/code-challenges-java#178]
## Tasklist
```[tasklist]
### Tasks
- [ ] https://github.com/divinedragon/code-challenges-java/issues/179
- [ ] https://github.com/divinedragon/code-challenges-java/issues/180
- [ ] https://github.com/divinedragon/code-challenges-java/issues/181
- [ ] https://github.com/divinedragon/code-challenges-java/issues/182
- [ ] https://github.com/divinedragon/code-challenges-java/issues/183
- [ ] https://github.com/divinedragon/code-challenges-java/issues/184
- [ ] https://github.com/divinedragon/code-challenges-java/issues/185
- [ ] https://github.com/divinedragon/code-challenges-java/issues/186
- [ ] https://github.com/divinedragon/code-challenges-java/issues/187
- [ ] https://github.com/divinedragon/code-challenges-java/issues/188
- [ ] https://github.com/divinedragon/code-challenges-java/issues/189
- [ ] https://github.com/divinedragon/code-challenges-java/issues/190
- [ ] https://github.com/divinedragon/code-challenges-java/issues/191
- [ ] https://github.com/divinedragon/code-challenges-java/issues/192
- [ ] https://github.com/divinedragon/code-challenges-java/issues/193
- [ ] https://github.com/divinedragon/code-challenges-java/issues/194
- [ ] https://github.com/divinedragon/code-challenges-java/issues/195
- [ ] https://github.com/divinedragon/code-challenges-java/issues/196
- [ ] https://github.com/divinedragon/code-challenges-java/issues/197
- [ ] https://github.com/divinedragon/code-challenges-java/issues/198
- [ ] https://github.com/divinedragon/code-challenges-java/issues/199
- [ ] https://github.com/divinedragon/code-challenges-java/issues/200
- [ ] https://github.com/divinedragon/code-challenges-java/issues/201
- [ ] https://github.com/divinedragon/code-challenges-java/issues/202
- [ ] https://github.com/divinedragon/code-challenges-java/issues/203
- [ ] https://github.com/divinedragon/code-challenges-java/issues/204
- [ ] https://github.com/divinedragon/code-challenges-java/issues/205
```

## Issues in the Epic
- [ ] #179
- [ ] #180
- [ ] #181
- [ ] #182
- [ ] #183
- [ ] #184
- [ ] #185
- [ ] #186
- [ ] #187
- [ ] #188
- [ ] #189
- [ ] #190
- [ ] #191
- [ ] #192
- [ ] #193
- [ ] #194
- [ ] #195
- [ ] #196
- [ ] #197
- [ ] #198
- [ ] #199
- [ ] #200
- [ ] #201
- [ ] #202
- [ ] #203
- [ ] #204
- [ ] #205
