### ISSUE TITLE
CodingBat - Logic1

### ISSUE THREAD

**Issue by divinedragon** [divinedragon/code-challenges-java#206]
## Tasklist
```[tasklist]
### Tasks
- [ ] https://github.com/divinedragon/code-challenges-java/issues/207
- [ ] https://github.com/divinedragon/code-challenges-java/issues/208
- [ ] https://github.com/divinedragon/code-challenges-java/issues/209
- [ ] https://github.com/divinedragon/code-challenges-java/issues/210
- [ ] https://github.com/divinedragon/code-challenges-java/issues/211
- [ ] https://github.com/divinedragon/code-challenges-java/issues/212
- [ ] https://github.com/divinedragon/code-challenges-java/issues/213
- [ ] https://github.com/divinedragon/code-challenges-java/issues/214
- [ ] https://github.com/divinedragon/code-challenges-java/issues/215
- [ ] https://github.com/divinedragon/code-challenges-java/issues/216
- [ ] https://github.com/divinedragon/code-challenges-java/issues/217
- [ ] https://github.com/divinedragon/code-challenges-java/issues/218
- [ ] https://github.com/divinedragon/code-challenges-java/issues/219
- [ ] https://github.com/divinedragon/code-challenges-java/issues/220
- [ ] https://github.com/divinedragon/code-challenges-java/issues/221
- [ ] https://github.com/divinedragon/code-challenges-java/issues/222
- [ ] https://github.com/divinedragon/code-challenges-java/issues/223
- [ ] https://github.com/divinedragon/code-challenges-java/issues/224
- [ ] https://github.com/divinedragon/code-challenges-java/issues/225
- [ ] https://github.com/divinedragon/code-challenges-java/issues/226
- [ ] https://github.com/divinedragon/code-challenges-java/issues/227
- [ ] https://github.com/divinedragon/code-challenges-java/issues/228
- [ ] https://github.com/divinedragon/code-challenges-java/issues/229
- [ ] https://github.com/divinedragon/code-challenges-java/issues/230
- [ ] https://github.com/divinedragon/code-challenges-java/issues/231
- [ ] https://github.com/divinedragon/code-challenges-java/issues/232
- [ ] https://github.com/divinedragon/code-challenges-java/issues/233
- [ ] https://github.com/divinedragon/code-challenges-java/issues/234
- [ ] https://github.com/divinedragon/code-challenges-java/issues/235
- [ ] https://github.com/divinedragon/code-challenges-java/issues/236
```

## Issues in the Epic
- [ ] #207
- [ ] #208
- [ ] #209
- [ ] #210
- [ ] #211
- [ ] #212
- [ ] #213
- [ ] #214
- [ ] #215
- [ ] #216
- [ ] #217
- [ ] #218
- [ ] #219
- [ ] #220
- [ ] #221
- [ ] #222
- [ ] #223
- [ ] #224
- [ ] #225
- [ ] #226
- [ ] #227
- [ ] #228
- [ ] #229
- [ ] #230
- [ ] #231
- [ ] #232
- [ ] #233
- [ ] #234
- [ ] #235
- [ ] #236
