### ISSUE TITLE
CodingBat - Warmup1

### ISSUE THREAD

**Issue by divinedragon** [divinedragon/code-challenges-java#43]
## Tasklist
```[tasklist]
### Tasks
- [x] https://github.com/divinedragon/code-challenges-java/issues/12
- [x] https://github.com/divinedragon/code-challenges-java/issues/13
- [x] https://github.com/divinedragon/code-challenges-java/issues/14
- [x] https://github.com/divinedragon/code-challenges-java/issues/15
- [x] https://github.com/divinedragon/code-challenges-java/issues/16
- [x] https://github.com/divinedragon/code-challenges-java/issues/17
- [x] https://github.com/divinedragon/code-challenges-java/issues/18
- [x] https://github.com/divinedragon/code-challenges-java/issues/19
- [x] https://github.com/divinedragon/code-challenges-java/issues/20
- [x] https://github.com/divinedragon/code-challenges-java/issues/21
- [x] https://github.com/divinedragon/code-challenges-java/issues/22
- [x] https://github.com/divinedragon/code-challenges-java/issues/23
- [x] https://github.com/divinedragon/code-challenges-java/issues/24
- [x] https://github.com/divinedragon/code-challenges-java/issues/25
- [x] https://github.com/divinedragon/code-challenges-java/issues/26
- [x] https://github.com/divinedragon/code-challenges-java/issues/27
- [x] https://github.com/divinedragon/code-challenges-java/issues/28
- [x] https://github.com/divinedragon/code-challenges-java/issues/29
- [x] https://github.com/divinedragon/code-challenges-java/issues/30
- [x] https://github.com/divinedragon/code-challenges-java/issues/31
- [x] https://github.com/divinedragon/code-challenges-java/issues/32
- [x] https://github.com/divinedragon/code-challenges-java/issues/33
- [x] https://github.com/divinedragon/code-challenges-java/issues/34
- [x] https://github.com/divinedragon/code-challenges-java/issues/35
- [x] https://github.com/divinedragon/code-challenges-java/issues/36
- [x] https://github.com/divinedragon/code-challenges-java/issues/37
- [x] https://github.com/divinedragon/code-challenges-java/issues/38
- [x] https://github.com/divinedragon/code-challenges-java/issues/39
- [x] https://github.com/divinedragon/code-challenges-java/issues/40
- [x] https://github.com/divinedragon/code-challenges-java/issues/41
- [x] https://github.com/divinedragon/code-challenges-java/issues/42
```

## Issues in the Epic
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
