### ISSUE TITLE
CodingBat - Warmup2

### ISSUE THREAD

**Issue by divinedragon** [divinedragon/code-challenges-java#44]
## Tasklist
```[tasklist]
### Tasks
- [x] https://github.com/divinedragon/code-challenges-java/issues/45
- [x] https://github.com/divinedragon/code-challenges-java/issues/46
- [x] https://github.com/divinedragon/code-challenges-java/issues/47
- [x] https://github.com/divinedragon/code-challenges-java/issues/48
- [x] https://github.com/divinedragon/code-challenges-java/issues/49
- [x] https://github.com/divinedragon/code-challenges-java/issues/50
- [x] https://github.com/divinedragon/code-challenges-java/issues/51
- [x] https://github.com/divinedragon/code-challenges-java/issues/52
- [x] https://github.com/divinedragon/code-challenges-java/issues/53
- [x] https://github.com/divinedragon/code-challenges-java/issues/54
- [x] https://github.com/divinedragon/code-challenges-java/issues/55
- [x] https://github.com/divinedragon/code-challenges-java/issues/56
- [x] https://github.com/divinedragon/code-challenges-java/issues/57
- [x] https://github.com/divinedragon/code-challenges-java/issues/58
- [x] https://github.com/divinedragon/code-challenges-java/issues/59
- [x] https://github.com/divinedragon/code-challenges-java/issues/60
- [x] https://github.com/divinedragon/code-challenges-java/issues/61
```

## Issues in the Epic
- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [x] #60
- [x] #61
